name: Build and Push Images to GHCR

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: orakysec/sistema-grupos-ofertas

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      # 1. API
      - name: Build and push API image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-api:latest ./api
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-api:latest

      # 2. Worker
      - name: Build and push Worker image
        run: |
          docker build -f ./api/Dockerfile.worker -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-worker:latest ./api
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-worker:latest

      # 3. Telegram Listener
      - name: Build and push Telegram Listener image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-telegram-listener:latest ./telegram-listener
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-telegram-listener:latest

      # 4. Frontend
      - name: Build and push Frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-frontend:latest ./frontend
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-frontend:latest
